name: "CodeQL"

on:
  push:
    branches: [ develop, main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ develop ]

jobs:
  analyze:
    name: Analyze
    
    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]
    
    runs-on: windows-2019
    permissions:
      actions: read
      contents: read
      security-events: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Download git submodules
      run: git submodule update --init --recursive

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build
      
    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build 
      run: cmake $GITHUB_WORKSPACE -DCMAKE_CXX_COMPILER=msvc -DCMAKE_DISABLE_FIND_PACKAGE_WindowsSDK=ON -T ClangCL
    
    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild (vcxproj on Windows)
      uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
