name: update-license

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 1 1 *" # 03:00 AM on January 1
  push:
    branches: [ task/automate-license-year ]
    
jobs:
  update-license-year:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branchName: task/update-license-{{currentYear}}
          commitTitle: Happy new year!
          prTitle: Happy new year!
          prBody: Automatically updated the license year
          assignees: LeonBrands
          labels: documentation
